### ISSUE TITLE
Duplicate text in the README

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/sinatra-views#10]
Hi. It looks like the section "Part 3: Multiple Routes with Multiple Views" repeats a few sentences that were in "Part 1: Rendering HTML". In Part 3, you have this paragraph:

"_**Run `shotgun` and go to http://localhost:9393 or the IP Address:PORT provided by the Learn IDE. Your "Hello World" text should now appear as an `<h1>`. Nice!**_ With `shotgun` running, head to http://localhost:9393/info . You should see "Testing the info page" rendered there. This lets us know that our route is defined properly. Next, let's have this route render a separate file instead. Inside of the `views` directory, create a file called `info.erb`. Add whatever HTML code you like."

The part of the paragraph that I bolded and italicized is from Part 1 and is not needed in Part 3.

Thanks for looking into this!
Sdcrouse

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
