### ISSUE TITLE
There's a misleading sentence in the README

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/sinatra-views#11]
Hi. Let me preface this by saying that I may be nitpicking here, so please feel free to take it or leave it. I noticed that in Part 3 of this lab, there's a sentence that says, "Add whatever HTML code you like." Then, it shows the following HTML:

```
<!DOCTYPE html>
<html>
    <head>
        <title>Info Page</title>
    </head>
    <body>
        <h1>Info Page</h1>
        <p>This is the info page: here's some information about me!</p>
    </body>
</html>
```

I think the sentence that I mentioned needs to be changed to something like "Add the following code into that file, and whatever else you like:".

My reason for this is that the tests won't pass without that specific HTML, contrary to what the original sentence implies.

Thanks for looking into this!
Sdcrouse

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
Thanks for your feedback!
