### ISSUE TITLE
Consider changing "hard coded" local host 9393

### ISSUE THREAD

**Issue by chemturion** [learn-co-curriculum/sinatra-views#8]
Is http://localhost:9393/ the most likely location of any user's `shotgun` sample? Would it be better to point the user to the `shotgun` command's output for the location? E.g. here's what my output was:

`[14:52:58] (master) sinatra-views-cb-000                                                                                                                                                                   
// ♥ shotgun                                                                                                                                                                                               
== Shotgun/Thin on http://138.68.11.226:30000/                                                                                                                                                             
Thin web server (v1.6.3 codename Protein Powder)                                                                                                                                                           
Maximum connections set to 1024                                                                                                                                                                            
Listening on 138.68.11.226:30000, CTRL+C to stop`

**Comment by curiositypaths** [comment]
Hi there,

Thank you for bringing this to our attention. WIth added a reference to the Learn IDE setup.

As always thank you for contributing!
